server:
  port: 8082

spring:
  data:
    mongodb:
      uri: ${DB_URL}
      database: ${DB_NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: false

keycloak:
  admin:
    username: ecom-admin
    password: 1234
    server-url: http://localhost:8443
    realm: ecom-app
    clientId: admin-cli
    clientUuid: a860bee5-d284-4c5b-8b94-c207c11e2681